### PR TITLE
cobaya: shorter prior spec: [min, max]

### PR DESCRIPTION
**Pull request by JesusTorrado**
This allows for:

    params:
      a:
        prior: [<min>, <max>]

### CODE REVIEW

**Comment by cmbant** [comment]
Allow list to also include loc, scale, or raise error if more than two entries?

**Comment by JesusTorrado** [comment]
Error control added. We'll do the rest later at some point (in cobaya first)

I guess by [min, max, loc, scale] you'd mean a truncnorm?

**Comment by cmbant** [comment]
I meant as a shortcut for
    ref:
      dist: norm
      loc: 
      scale: 
Normally people probably would want to give the proposal width.

**Comment by JesusTorrado** [comment]
But this was "prior: [min, max]", not "param: [min, max]"

**Comment by cmbant** [comment]
Ah!

**Comment by JesusTorrado** [comment]
Implementing that in Cobaya right now. Please don't merge just yet.

**Comment by JesusTorrado** [comment]
Done in Cobaya (allows for 2, 4 and 5 numbers, meaning prior, gaussian ref, proposal). Does not need anything else here (just this one). You can merge if you want.

**Pull request merged**
