### PR TITLE
Storing sampler type and treat Nested Sampler samples correctly (issue #27)

### PR DESCRIPTION
**Pull request by JesusTorrado**
Hi @cmbant and @williamjameshandley,

Here is the first step of what I was proposing re #27: store the sampler type as an attribute of `MCSamples`. If @cmbant likes the idea and the way/places the changes have been introduced, I'll try yo do step 2: shuffle the samples before calling `MCSamples.updateBaseStatistics()`.

Cheers!

### CODE REVIEW

**Comment by williamjameshandley** [comment]
I assume this would be triggered by the user providing a `sampler='nested'` optional argument. I can't think of any way to automatically detect whether it's a nested sampling chain. Perhaps we could also add some functionality to test whether it probably is an NS chain (e.g. if the .txt file is in likelihood order, or has extremely small weights).

**Comment by JesusTorrado** [comment]
If the chains are from Cobaya, it's triggered by checking the `sampler` field in the info.

**Comment by cmbant** [comment]
Does "sampler=nested" refer specifically to polychord in Coabaya, or generically any nested implementation?I guess we should also have a way to make it work consistently with plain text files, e.g. sampler= in properties.ini equivalent.

Shuffling seems a bit of a hack, better to come up with some alternative appropriate number for the effective number of samples (@williamjameshandley ?).

**Comment by JesusTorrado** [comment]
> Does "sampler=nested" refer specifically to polychord in Coabaya, or generically any nested implementation?I guess we should also have a way to make it work consistently with plain text files, e.g. sampler= in properties.ini equivalent.

Of course not. The modification is just a basis. One could definitely set it in `properties.ini` or `settings` (which one would be better here?)

**Comment by cmbant** [comment]
.properties.ini is the only place currently for specific metadata for a particular chain. burn_removed=T already specifies not to remove burn in; ideally this would be consistent.
More generally we could have two variables: one to never remove burn in (currently burn_removed=T),  and another to specify something about how to determine the effective number of samples (not sure what though...).

**Comment by williamjameshandley** [comment]
> Shuffling seems a bit of a hack, better to come up with some alternative appropriate number for the effective number of samples

If the nested sampler is 'perfect' (multinest: `eff->0`, polychord: `num_repeats->infinity` -- often not an unreasonable approximation -- then the samples are independent. The effective number as would usually be put into kernel density estimators would then be `neff = sum(weights)^2 / sum(weights^2)`, (as it is in [scipy]( https://github.com/scipy/scipy/blob/master/scipy/stats/kde.py))

**Comment by cmbant** [comment]
I'm not sure "independent" is the right word (since the likelihood values are changing in a predictable way) but I see what you mean. That would certainly be a reasonable fallback (and equivalent to Jesus' shuffling suggestion but with zero cost).

**Comment by cmbant** [comment]
I pushed change to set uncorrelated effective samples if nested or uncorrelated.

**Pull request merged**
